name: Deploy to Server
on:
  push:
    branches: [ master ]  # 只在 master 分支 push 时触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Git Pull
        run: |
          ssh -o StrictHostKeyChecking=no root@8.138.189.239 'cd /var/www/html && git pull origin master'
