name: Auto Deploy to Server
on:
  push:
    branches: [ master ]  # 只在 master 分支 push 时触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # 检出代码
      - uses: actions/checkout@v4

      #设置SSH密钥
      
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

# 自动同步到服务器
      - name: Rsync Deployment
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ root@8.138.189.239:/var/www/html/
            
      

